# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'
#inhibit_all_warnings!

target 'Bmemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bmemo
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'ObjectMapper',    '~> 2.2.1'

end
